import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const github = 'https://github.com/hardikdhingra150';
const projects = [
  {name:'HealthQrApp',type:'HEALTHCARE / WEB APPLICATION',text:'Medical records, one scan away. Store, organize, and access healthcare documents through a single QR code.',tags:['Flask','MongoDB','HTML / CSS'],repo:'HealthQrApp',mark:'HQ',color:'red'},
  {name:'MamaCare',type:'HEALTHCARE / PRODUCT',text:'A care-centered application exploring how thoughtful digital tools can support everyday healthcare needs.',tags:['Healthcare','Full stack','Product'],repo:'MamaCare',mark:'MC',color:'cream'},
  {name:'Trackrail',type:'TRANSPORT / WEB APPLICATION',text:'An exploration of transport tracking, movement, and real-world data brought together in a web application.',tags:['Tracking','Web app','Data'],repo:'trackrail',mark:'TR',color:'gray'},
  {name:'errorbuddy',type:'DEVELOPER TOOLS / UTILITY',text:'Less friction in the debugging loop. A developer-helper concept for understanding errors and getting back to building.',tags:['Developer tools','Debugging'],repo:'errorbuddy',mark:'EB',color:'gray'},
  {name:'Healix',type:'HEALTHCARE / CONCEPT',text:'A healthcare product concept shaped around practical user needs and clearer access to useful information.',tags:['Healthcare','Product concept'],repo:'Healix',mark:'HX',color:'red'},
  {name:'Dronaconnect',type:'EDUCATION / PRODUCT',text:'An education-centered product idea exploring a more connected experience for students and their community.',tags:['Education','Product'],repo:'Dronaconnect',mark:'DC',color:'cream'},
];
const archive = ['Hackrons','luna-care-app','Cineverse','document-qa','Expense_Tracker_App','Doracare','AI-Agent','rezzops'];
const links = [['about','The driver'],['projects','The garage'],['skills','Under the hood'],['contact','Team radio']];
function Arrow(){return <span aria-hidden="true">↗</span>}
function External({href,children,...props}){return <a href={href} target="_blank" rel="noopener noreferrer" {...props}>{children}</a>}
function Label({n,children}){return <div className="section-label"><span className="sector">S{n}</span><span>{children}</span><span className="label-line"/></div>}

function Ignition({onEnter,reduced}){
 const [phase,setPhase]=useState('ready');const [lights,setLights]=useState(0);const timers=useRef([]);const button=useRef(null);
 useEffect(()=>{button.current?.focus();return ()=>timers.current.forEach(clearTimeout)},[]);
 useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow='hidden';const onKey=e=>{if(e.key==='Escape')onEnter()};window.addEventListener('keydown',onKey);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',onKey)}},[onEnter]);
 function ignite(){if(phase!=='ready')return;if(reduced){onEnter();return}setPhase('starting');for(let i=1;i<=5;i++)timers.current.push(setTimeout(()=>setLights(i),i*180));timers.current.push(setTimeout(()=>setPhase('go'),1300));timers.current.push(setTimeout(onEnter,1800));}
 return <div className={`ignition ${phase}`} role="dialog" aria-modal="true" aria-labelledby="ignition-title"><div className="intro-top"><a className="brand" href="#" onClick={e=>e.preventDefault()}>HD<span> / 01</span></a><span className="mono">HARDIK DHINGRA · PORTFOLIO</span></div><div className="ignition-center"><div className="start-lights" aria-hidden="true">{[1,2,3,4,5].map(i=><i key={i} className={lights>=i?'on':''}/>)}</div><span className="eyebrow">A LITTLE AMBITION. FULL THROTTLE.</span><h1 id="ignition-title">EVERYTHING STARTS<br/>WITH A <em>SPARK.</em></h1><p>Welcome to my corner of the grid.</p><button ref={button} className="ignite-button" onClick={ignite} disabled={phase!=='ready'}><span className="power" aria-hidden="true">⏻</span>{phase==='ready'?'IGNITE PORTFOLIO':phase==='go'?'LIGHTS OUT. LET’S GO.':'STARTING THE SESSION…'}<Arrow/></button><button className="skip" onClick={onEnter}>Skip intro <span>→</span></button><span className="sr-only" role="status">{phase==='starting'?'Starting portfolio':phase==='go'?'Portfolio ready':''}</span></div><div className="intro-bottom mono"><span>CREATIVE ENGINEERING / EST. IN GURUGRAM</span><span>READY WHEN YOU ARE <i className="status-dot"/></span></div></div>
}
function ProjectCard({project:p,index}){return <article className={`project-card reveal ${p.color}`}><div className="project-art" aria-hidden="true"><span className="art-caption">HD ENGINEERING / PROJECT {String(index+1).padStart(2,'0')}</span><strong>{p.mark}</strong><span className="art-lines"/><span className="art-bottom">DESIGN. BUILD. ITERATE. <span>↗</span></span></div><div className="project-info"><div className="project-meta"><span>0{index+1}</span><span>{p.type}</span></div><h3>{p.name}</h3><p>{p.text}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><External href={`${github}/${p.repo}`} className="project-link">Explore the build <Arrow/></External></div></article>}
function App(){
 const [intro,setIntro]=useState(true),[menu,setMenu]=useState(false),[motion,setMotion]=useState(()=>!window.matchMedia('(prefers-reduced-motion: reduce)').matches),[progress,setProgress]=useState(0),[active,setActive]=useState('about');
 const entered=useRef(false);const home=useRef(null);const enter=React.useCallback(()=>{setIntro(false);entered.current=true;setTimeout(()=>home.current?.focus(),30)},[]);
 useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setMotion(!query.matches);query.addEventListener('change',update);return()=>query.removeEventListener('change',update)},[]);
 useEffect(()=>{document.documentElement.classList.toggle('motion-off',!motion);return()=>document.documentElement.classList.remove('motion-off')},[motion]);
 useEffect(()=>{let frame=0;const update=()=>{const length=document.documentElement.scrollHeight-innerHeight;setProgress(length>0?Math.min(100,Math.round(scrollY/length*100)):0);frame=0};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update)};addEventListener('scroll',scroll,{passive:true});addEventListener('resize',scroll);update();return()=>{removeEventListener('scroll',scroll);removeEventListener('resize',scroll);cancelAnimationFrame(frame)}},[]);
 useEffect(()=>{if(intro)return;const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));const nav=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id)}),{rootMargin:'-15% 0px -55% 0px'});links.forEach(([id])=>nav.observe(document.getElementById(id)));return()=>{io.disconnect();nav.disconnect()}},[intro]);
 return <>{intro&&<Ignition onEnter={enter} reduced={!motion}/>}<div className={`site ${!intro?'entered':''}`} inert={intro?true:undefined}>
 <a href="#main" className="skip-link">Skip to content</a><header className="nav"><a className="brand" href="#top" aria-label="Hardik Dhingra home">HD<span> / 01</span></a><nav aria-label="Main navigation" className={menu?'open':''}>{links.map(([id,label],i)=><a href={`#${id}`} className={active===id?'active':''} key={id} onClick={()=>setMenu(false)}><small>0{i+1}</small>{label}</a>)}</nav><a className="nav-contact" href="mailto:hardikdhingra150@gmail.com">LET’S TALK <Arrow/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Toggle navigation">{menu?'CLOSE':'MENU'}</button></header>
 <main id="main"><section className="hero" id="top"><div className="hero-top mono"><span><i className="status-dot"/> AVAILABLE FOR COLLABORATIONS</span><span>GURUGRAM, INDIA <span className="flag">▰</span></span></div><div className="hero-art" aria-hidden="true"/><div className="hero-number" aria-hidden="true">01</div><div className="hero-content"><span className="eyebrow"><span className="red-line"/> DEVELOPER. BUILDER. ALWAYS PUSHING.</span><h1 ref={home} tabIndex={-1}>HARDIK<br/><em>DHINGRA.</em></h1><div className="hero-description"><span className="tiny-cross" aria-hidden="true">+</span><p>I turn curiosity into code.<br/>Building thoughtful digital experiences,<br/>one iteration closer to the limit.</p></div><div className="hero-actions"><a href="#projects" className="button red-button">EXPLORE THE GARAGE <Arrow/></a><a href="./Had_Resume.pdf" className="text-link" target="_blank" rel="noopener noreferrer">DRIVER PROFILE <span>↓</span></a></div></div><div className="car-caption mono"><span>HD—01</span><span>BUILT TO PUSH LIMITS.</span><i/></div><div className="hero-bottom mono"><span>REACT + JAVASCRIPT <b>/</b> CREATIVE DEVELOPMENT</span><a href="#about">SCROLL TO GET UP TO SPEED <span>↓</span></a></div></section>
 <div className="ticker" aria-hidden="true"><div>{[0,1,2,3].map(n=><React.Fragment key={n}><span>BUILD WITH INTENT</span><i>✳</i><span>PUSH THE POSSIBILITIES</span><i>✳</i></React.Fragment>)}</div></div>
 <section className="about section" id="about"><Label n="1">THE DRIVER / BEHIND THE BUILD</Label><div className="about-grid"><div className="reveal"><h2>DRIVEN BY<br/>CURIOSITY.<br/><em>BUILT FOR MORE.</em></h2><div className="driver-sign">Hardik Dhingra <span>↗</span></div></div><div className="about-story reveal"><span className="eyebrow">A DEVELOPER’S MIND. A RACER’S DRIVE.</span><p className="lead">Hey, I’m Hardik. A Computer Science student who learns best with his hands on the wheel.</p><p>I build web applications, backend systems, and experiments that turn rough ideas into useful products. React and JavaScript power my frontend work; Python and Flask help bring the logic to life.</p><p>My approach is simple: build, test, learn, and go again. Outside the editor, you’ll find me playing badminton or cricket, experimenting in the kitchen, or chasing the next good idea.</p><div className="stats"><div><strong>3<span>RD</span></strong><small>YEAR / B.TECH CS</small></div><div><strong>24<span>+</span></strong><small>GITHUB REPOSITORIES</small></div><div><strong>∞</strong><small>ROOM TO IMPROVE</small></div></div></div></div></section>
 <section className="projects section" id="projects"><Label n="2">THE GARAGE / SELECTED WORK</Label><div className="section-heading reveal"><h2>ENGINEERED TO<br/><em>MAKE AN IMPACT.</em></h2><p>Different challenges. The same drive to build<br/>something that earns its place.</p></div><div className="project-grid">{projects.map((p,i)=><ProjectCard project={p} index={i} key={p.repo}/>)}</div><details className="archive"><summary>MORE FROM THE GARAGE <span>08 BUILDS <b>+</b></span></summary><div className="archive-grid">{archive.map((repo,i)=><External href={`${github}/${repo}`} key={repo}><span>0{i+1}</span>{repo.replaceAll('_',' ')}<Arrow/></External>)}</div></details></section>
 <section className="skills section" id="skills"><Label n="3">UNDER THE HOOD / TECH STACK</Label><div className="skills-grid"><div className="reveal"><h2>THE RIGHT TOOLS.<br/><em>NO SHORTCUTS.</em></h2><p>Every build has a different setup.<br/>These are the tools in my garage.</p><div className="engine-spec"><span className="mono">PRIMARY FRONTEND ENGINE</span><strong>REACT <i>+</i> JS</strong><div className="rev-meter" aria-hidden="true">{Array.from({length:22},(_,i)=><i key={i} style={{'--i':i}}/>)}</div><span className="mono">COMPONENTS / INTERACTION / EXPERIENCE</span></div></div><div className="stack-list reveal">{[['01','Frontend','React · JavaScript · HTML · CSS','Interfaces built around reusable components and responsive layouts.'],['02','Backend','Python · Flask · APIs','Practical application logic and clean connections between services.'],['03','Data & storage','SQL · MongoDB','Relational and document databases, chosen for the problem.'],['04','Engineering','Git · C · C++','Version control, fundamentals, and a habit of continuous iteration.']].map(([n,name,stack,description])=><article key={n}><span className="stack-n">{n}</span><div><h3>{name}</h3><strong>{stack}</strong><p>{description}</p></div><span className="stack-plus" aria-hidden="true">+</span></article>)}</div></div></section>
 <section className="resume-strip"><div><span className="eyebrow">THE FULL DRIVER PROFILE</span><h2>ALL THE DETAILS. <em>ONE DOWNLOAD.</em></h2></div><a href="./Had_Resume.pdf" download className="button">DOWNLOAD RÉSUMÉ <span>↓</span></a></section>
 <section className="contact section" id="contact"><Label n="4">TEAM RADIO / GET IN TOUCH</Label><div className="contact-top reveal"><div className="contact-kicker"><i className="status-dot"/> OPEN TO INTERNSHIPS & COLLABORATIONS</div><h2>GOT AN IDEA?<br/>LET’S <em>IGNITE IT.</em></h2><a className="contact-email" href="mailto:hardikdhingra150@gmail.com">hardikdhingra150@gmail.com <Arrow/></a></div><div className="contact-bottom"><p>Good work starts with a conversation.<br/>Let’s build something worth putting on the grid.</p><div><External href={github}>GITHUB <Arrow/></External><External href="https://www.linkedin.com/in/hardik-dhingra-ab2264280">LINKEDIN <Arrow/></External></div></div></section>
 </main><footer><a className="brand" href="#top">HD<span> / 01</span></a><span>© {new Date().getFullYear()} HARDIK DHINGRA</span><span>BUILT WITH REACT. DRIVEN BY CURIOSITY.</span><button onClick={()=>{scrollTo({top:0,behavior:'instant'});setIntro(true)}}>REPLAY IGNITION ↻</button></footer><div className="session-bar"><span><i className="status-dot"/> PORTFOLIO SESSION</span><div className="session-progress"><i style={{width:`${progress}%`}}/></div><span>EXPLORED {String(progress).padStart(2,'0')}%</span><button onClick={()=>setMotion(!motion)} aria-pressed={!motion}>{motion?'Ⅱ PAUSE MOTION':'▶ RESUME MOTION'}</button></div>
 </div></>
}
createRoot(document.getElementById('root')).render(<App/>);
